version: "3.3"
services:
  web_prod:
    container_name: prod-hello
    build:
     context: .
     dockerfile: Dockerfile.prod 
    ports:
      - '8080:80'
    env_file:
      - prod.env
       
    

    
