# Stage 1: Build the React application
FROM node:20-alpine3.18 as build
WORKDIR /app
COPY *.json ./
RUN npm install
COPY . .
RUN  npm run build

# Stage 2: Serve the React application from Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
