version: "3.3"
services:
  web:
    container_name: dev-hello
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - '3000:3000'
    volumes:
    - .:/app
    env_file:
      - .env
    

    
